version: '3'
services:
  go:
    image: golang-todo-list-cli-image
    container_name: golang-todo-list-cli-container
    build:
      context: .
      dockerfile: ./container/Dockerfile
    stdin_open: true
    tty: true
    working_dir: /app
    volumes:
      - ./src:/app
    environment:
      TZ: Asia/Tokyo
    env_file:
      - .env
